version: "3.8"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DATABASE: bsi
  VUE_APP_SERVER_PORT: 8000

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql
  backend:
    image: soltys222/vue-nest_backend:1.0.1
    depends_on:
      - mysql
    expose:
      - 3000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 3000:3000
    links:
      - mysql
    command: npm run start
  frontend:
    image: soltys222/vue-nest_frontend:1.0.1
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - backend
    command: npm run serve
